# Generated by Django 5.0.4 on 2024-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('head_of_department', models.CharField(max_length=100)),
                ('number_of_staff', models.IntegerField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Department_Table',
            },
        ),
    ]
