# Generated by Django 5.0.4 on 2024-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IT', 'Information Technology'), ('CSE', 'Computer Science and Engineering'), ('AERO', 'Aerospace Engineering')], max_length=100),
        ),
    ]
