# Generated by Django 5.0.4 on 2024-04-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_alter_department_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Electronics and Communication Engineering', 'ECE'), ('Electrical and Electronics Engineering', 'EEE'), ('Information Technology', 'IT'), ('Computer Science and Engineering', 'CSE'), ('Aerospace Engineering', 'AERO')], max_length=100),
        ),
    ]
